import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import type { TerminalBlock } from '../src/components/terminal/terminal.types';
import { parseTerminalMarkdown } from '../src/content/terminalMarkdown';

const SCRIPT_DIRECTORY = path.dirname(fileURLToPath(import.meta.url));
export const WEB_ROOT = path.resolve(SCRIPT_DIRECTORY, '..');
export const MARKDOWN_ROOT = path.join(WEB_ROOT, 'src', 'content', 'markdown');
export const GENERATED_FILE = path.join(WEB_ROOT, 'src', 'content', 'generated', 'terminalContent.ts');

export const CONTENT_SOURCES = [
  ['mainContent', 'main.md'],
  ['aboutContent', 'about.md'],
  ['cvContent', 'cv.md'],
] as const;

export type GeneratedContent = readonly (readonly [string, readonly TerminalBlock[]])[];

export async function compileTerminalContent(): Promise<boolean> {
  const content: Array<readonly [string, readonly TerminalBlock[]]> = [];

  for (const [exportName, relativePath] of CONTENT_SOURCES) {
    const absolutePath = path.join(MARKDOWN_ROOT, relativePath);
    const source = await readFile(absolutePath, 'utf8');
    const displayPath = path.relative(WEB_ROOT, absolutePath).replaceAll('\\', '/');
    content.push([exportName, parseTerminalMarkdown(source, displayPath)]);
  }

  const generated = renderGeneratedModule(content);
  const previous = await readFile(GENERATED_FILE, 'utf8').catch(() => null);
  if (previous === generated) {
    return false;
  }

  await mkdir(path.dirname(GENERATED_FILE), { recursive: true });
  await writeFile(GENERATED_FILE, generated, 'utf8');
  return true;
}

export function renderGeneratedModule(content: GeneratedContent): string {
  const exports = content.map(([name, blocks]) => (
    `export const ${name} = ${JSON.stringify(blocks, null, 2)} as const satisfies readonly TerminalBlock[];`
  ));

  return [
    '// This file is generated by scripts/compile-terminal-content.ts. Do not edit manually.',
    "import type { TerminalBlock } from '@/components/terminal/terminal.types';",
    '',
    ...exports.flatMap((entry) => [entry, '']),
  ].join('\n');
}

async function main(): Promise<void> {
  const changed = await compileTerminalContent();
  console.log(changed ? 'Generated terminal Markdown content.' : 'Terminal Markdown content is up to date.');
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
