[package]
name = "zhdanov_wire_world"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.11.0" }
anyhow = { version = "1.0" }
indexmap = { version = "1.9.3" }
bevy_tweening = { version = "0.8.0" }
