name: Docker Image CI

on:
  push:
    paths:
      - 'tools/**'

jobs:
  build:

    runs-on: ubuntu-latest
    environment: docker-hub

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./tools/Dockerfile
        push: true
        tags: zhdanovdev/rust-wasm-builder:latest